steps:
  # npm install
  - id: npm install
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # run build
  - id: build
    name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  # run tests
  - id: test
    name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    
  # Build movies-service-nestjs image
  - id: build docker image
    name: gcr.io/cloud_builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/movies-service-nestjs:$COMMIT_SHA
      - .

  # Push movies-service-nestjs image to Google Cloud Registry
  - id: push docker image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/movies-service-nestjs:$COMMIT_SHA

  # Configure a kubectl workspace for this project
  - id: configure kubectl
    name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1
      - KUBECONFIG=/workspace/.kube/config
  - id: kustomize
    name: 'gcr.io/$PROJECT_ID/kustomize'
    args:
    - 'edit'
    - 'set'
    - 'image'
    - 'gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/movies-service-nestjs:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'
      - 'GCLOUD_PROJECT=movies-app-312313'
  - id: deploy
    name: 'gcr.io/$PROJECT_ID/kustomize'
    args:
    - 'build'
    - '.'
    env:
      - 'APPLY=true'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'
      - 'GCLOUD_PROJECT=movies-app-312313'