apiVersion: v1
kind: Service
metadata:
  name: movies-service-nestjs
spec:
  type: NodePort
  selector:
    app: movies-service-nestjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
