apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service-nestjs-deployment
  labels:
    app: movies-service-nestjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies-service-nestjs
  template:
    metadata:
      labels:
        app: movies-service-nestjs
    spec:
      containers:
        - name: movies-service-nestjs
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 3000
